# which benchmarks to run
benchmarks = '../../benchmarks/*/*.bril'
# how to extract the performance metric from stderr
extract = '(\d+)'

[runs.norm_first]
pipeline = [
  "bril2json",
  "python3 loop_norm.py",
  "python3 ssa.py",
  "brili {args}",
]

[runs.ssa_first]
pipeline = [
  "bril2json",
  "python3 ssa.py",
  "python3 loop_norm.py",
  "brili {args}",
]