# which benchmarks to run
benchmarks = '../../benchmarks/*/*.bril'
# how to extract the performance metric from stderr
extract = '(\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "python3 loop_norm.py",
  "python3 ssa.py",
  "brili {args}",
]

[runs.licm]
pipeline = [
  "bril2json",
  "python3 loop_norm.py",
  "python3 ssa.py",
  "python3 licm.py",
  "python3 remove_nops.py",
  "brili {args}",
]